### ISSUE TITLE
segmentation violation on specific yaml

### ISSUE THREAD

**Issue by gifnksm** [rhysd/actionlint#193]
actionlint segfaults when this yaml file is in `.github/workflows/`:

```yaml
name: CI

jobs:
  foo:
    steps:
      - uses: actions/checkout@v3
        continue-on-error: ${{ matrix.os == "macos-latest" }}
```

```console
$ actionlint
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x5aa6aa]

goroutine 1 [running]:
github.com/rhysd/actionlint.(*RuleExpression).checkBool(0xc0000a4100, 0xc00000c330)
        /home/runner/work/actionlint/actionlint/rule_expression.go:590 +0x8a
github.com/rhysd/actionlint.(*RuleExpression).VisitStep(0xc0000a4100, 0xc000074410)
        /home/runner/work/actionlint/actionlint/rule_expression.go:251 +0x17e
github.com/rhysd/actionlint.(*Visitor).visitStep(0xc0000ad798, 0xc000074410)
        /home/runner/work/actionlint/actionlint/pass.go:139 +0x117
github.com/rhysd/actionlint.(*Visitor).visitJob(0xc0000ad798, 0xc0000f8000)
        /home/runner/work/actionlint/actionlint/pass.go:109 +0x189
github.com/rhysd/actionlint.(*Visitor).Visit(0xc0000ad798, 0xc0000743c0)
        /home/runner/work/actionlint/actionlint/pass.go:68 +0x133
github.com/rhysd/actionlint.(*Linter).check(0xc0000a4080, {0xc00002215f, 0x18}, {0xc0000f0000, 0x82, 0x200}, 0xc00000c2b8, 0x4934ed?, 0xc000026a00)
        /home/runner/work/actionlint/actionlint/linter.go:514 +0x10fa
github.com/rhysd/actionlint.(*Linter).LintFile(0xc0000a4080, {0xc000022150, 0x27}, 0x592111?)
        /home/runner/work/actionlint/actionlint/linter.go:387 +0x36a
github.com/rhysd/actionlint.(*Linter).LintFiles(0x677110?, {0xc000010640?, 0x1?, 0x591305?}, 0xc0000add08?)
        /home/runner/work/actionlint/actionlint/linter.go:268 +0x330
github.com/rhysd/actionlint.(*Linter).LintRepository(0xc0000a4080, {0x6242b0, 0x1})
        /home/runner/work/actionlint/actionlint/linter.go:256 +0x369
github.com/rhysd/actionlint.(*Command).runLinter(0xc0000dfc20, {0xc000010200?, 0x0, 0x0}, 0xc0000e0e10, 0x0)
        /home/runner/work/actionlint/actionlint/command.go:92 +0x198
github.com/rhysd/actionlint.(*Command).Main(0xc0000dfc20, {0xc000010200, 0x1, 0x1})
        /home/runner/work/actionlint/actionlint/command.go:181 +0x6d7
main.main()
        /home/runner/work/actionlint/actionlint/cmd/actionlint/main.go:15 +0xd6

$ actionlint --version
1.6.15
installed by downloading from release page
built with go1.18.3 compiler for linux/amd64

$ uname -a
Linux thyme 5.18.16-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:04 +0000 x86_64 GNU/Linu
```

**Comment by gifnksm** [comment]
this yaml does not trigger segfaults (double quote vs single quote):

```yaml
name: CI

jobs:
  foo:
    steps:
      - uses: actions/checkout@v3
        continue-on-error: ${{ matrix.os == 'macos-latest' }}
```

```console
$  actionlint
.github/workflows/ci.yml:4:3: "runs-on" section is missing in job "foo" [syntax-check]
  |
4 |   foo:
  |   ^~~~
.github/workflows/ci.yml:7:32: property "os" is not defined in object type {} [expression]
  |
7 |         continue-on-error: ${{ matrix.os == 'macos-latest' }}
  |                                ^~~~~~~~~
```

**Comment by rhysd** [comment]
Thank you for reporting this. I could reproduce.
